-- Wrap auth.uid()/current_setting() in RLS policy predicates in (select ...) so
-- Postgres evaluates each once per statement (an InitPlan) instead of once per row --
-- the Supabase-documented RLS perf pattern. Covers USING and WITH CHECK. Predicate-
-- equivalent (row visibility unchanged). Generated by 'pgrls fix --rule PERF001'
-- (pgrls 0.44.0) and verified on Postgres 16 (PERF001 -> 0).

-- [PERF001] Wrap auth function call(s) in policy 'Users can create own chats' on public.chats so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can create own chats" ON public.chats
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can delete own chats' on public.chats so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can delete own chats" ON public.chats
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can update own chats' on public.chats so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update own chats" ON public.chats
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view own chats' on public.chats so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view own chats" ON public.chats
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can create own documents' on public.documents so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can create own documents" ON public.documents
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can delete own documents' on public.documents so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can delete own documents" ON public.documents
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can insert their own documents' on public.documents so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can insert their own documents" ON public.documents
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can update own documents' on public.documents so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update own documents" ON public.documents
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can update their own documents' on public.documents so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update their own documents" ON public.documents
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view own documents' on public.documents so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view own documents" ON public.documents
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view their own documents' on public.documents so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view their own documents" ON public.documents
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can delete their own files' on public.file_uploads so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can delete their own files" ON public.file_uploads
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can insert their own files' on public.file_uploads so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can insert their own files" ON public.file_uploads
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view their own files' on public.file_uploads so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view their own files" ON public.file_uploads
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can create messages in their chats' on public.messages so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can create messages in their chats" ON public.messages
    WITH CHECK ((SELECT auth.uid()) IN (SELECT chats.user_id FROM chats WHERE chats.id = messages.chat_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can view messages from their chats' on public.messages so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view messages from their chats" ON public.messages
    USING ((SELECT auth.uid()) IN (SELECT chats.user_id FROM chats WHERE chats.id = messages.chat_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can create own suggestions' on public.suggestions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can create own suggestions" ON public.suggestions
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view own suggestions' on public.suggestions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view own suggestions" ON public.suggestions
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can update own profile' on public.users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update own profile" ON public.users
    USING ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view own profile' on public.users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view own profile" ON public.users
    USING ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can create votes on their chats' on public.votes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can create votes on their chats" ON public.votes
    WITH CHECK ((SELECT auth.uid()) IN (SELECT chats.user_id FROM chats WHERE chats.id = votes.chat_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can delete votes on their chats' on public.votes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can delete votes on their chats" ON public.votes
    USING ((SELECT auth.uid()) IN (SELECT chats.user_id FROM chats WHERE chats.id = votes.chat_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can update votes on their chats' on public.votes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update votes on their chats" ON public.votes
    USING ((SELECT auth.uid()) IN (SELECT chats.user_id FROM chats WHERE chats.id = votes.chat_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can view votes on their chats' on public.votes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view votes on their chats" ON public.votes
    USING ((SELECT auth.uid()) IN (SELECT chats.user_id FROM chats WHERE chats.id = votes.chat_id));
